"""BOS 服务注册表 — POC_SERVICES 定义"""

from __future__ import annotations

import os

from .services_types import (  # ISC-34 第一步: types/patterns 提取 (God Module 拆分)
    BOS_URI_DOMAIN_PATTERN,
    BOS_URI_DOMAINS,
    BOS_URI_PATTERN,
    BosService,
    Transport,
)

# re-export 保下游兼容 (from agora.mcp.resolver.services import BosService 仍工作)
__all__ = [
    "BOS_URI_DOMAINS",
    "BOS_URI_DOMAIN_PATTERN",
    "BOS_URI_PATTERN",
    "BosService",
    "Transport",
]


def _with_uv_package(service: BosService) -> list[str]:
    """Normalize legacy uv run commands for workspace packages."""
    cmd = list(service.command)
    if len(cmd) < 2 or cmd[0] != "uv" or cmd[1] != "run":
        return cmd
    if "--package" in cmd:
        return cmd
    if "--directory" not in cmd:
        return cmd
    if not service.package:
        return cmd
    return ["uv", "run", "--package", service.package, *cmd[2:]]


# ── POC_SERVICES: 声明式加载 (YAML > 硬编码 fallback) ─────────
# 1. 加载顺序: AGORA_BOS_REGISTRY 环境变量 → etc/bos-services.yaml → 硬编码 fallback
# 2. `AGORA_BOS_REGISTRY=none` 强制使用硬编码 fallback
# 3. 新增路由请编辑 etc/bos-services.yaml, 勿改本文件

_FALLBACK_SERVICES: list[BosService] = [
    # ════════════════════════════════════════════════════════════════
    # Domain: memory
    # ════════════════════════════════════════════════════════════════
    BosService(
        uri="bos://memory/inbox/status",
        domain="memory",
        package="agora",
        action="inbox-status",
        transport="stdio",
        command=["python", "-m", "agora.server.tools_bos"],
        description="BOS Inbox 神经网状态统计",
    ),
    BosService(
        uri="bos://memory/inbox/search",
        domain="memory",
        package="agora",
        action="inbox-search",
        transport="stdio",
        command=["python", "-m", "agora.server.tools_bos"],
        description="BOS Inbox 语义检索",
    ),
    BosService(
        uri="bos://memory/inbox/pending",
        domain="memory",
        package="agora",
        action="inbox-pending",
        transport="stdio",
        command=["python", "-m", "agora.server.tools_bos"],
        description="BOS Inbox 待办快照与多源预览",
    ),
    BosService(
        uri="bos://memory/inbox/watch",
        domain="memory",
        package="agora",
        action="inbox-watch",
        transport="stdio",
        command=["python", "-m", "agora.server.tools_bos"],
        description="BOS Inbox 实时事件驱动监控与紧急提醒快照 (v2.0)",
    ),
    BosService(
        uri="bos://memory/inbox/archive",
        domain="memory",
        package="agora",
        action="inbox-archive",
        transport="stdio",
        command=["python", "-m", "agora.server.tools_bos"],
        description="BOS Inbox 待办事宜归档闭环接口 (Lifecycle Archive)",
    ),
    BosService(
        uri="bos://memory/inbox/triage",
        domain="memory",
        package="agora",
        action="inbox-triage",
        transport="internal",
        module_path="agora.server.tools_bos",
        func_name="bos_inbox_triage",
        description="BOS Inbox 公文与待办事项智能分类分拣与紧急度测算引擎 (Triage Engine)",
    ),
    BosService(
        uri="bos://memory/inbox/draft",
        domain="memory",
        package="agora",
        action="inbox-draft",
        transport="internal",
        module_path="agora.server.tools_bos",
        func_name="bos_inbox_draft",
        description="BOS Inbox 智能拟办意见与风险提示批复草拟引擎 (Draft Assistant)",
    ),
    BosService(
        uri="bos://memory/kos/search",
        domain="memory",
        package="kos",
        action="search",
        transport="stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/knowledge/kairon",
            "python",
            "-m",
            "kos.cli",
            "search",
        ],
        description="KOS 知识图谱检索入口 (P33-W1 战役 2 起步)",
    ),
    BosService(
        uri="bos://memory/kos/ingest",
        domain="memory",
        package="kos",
        action="ingest",
        transport="stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/knowledge/kairon",
            "python",
            "-m",
            "kos.cli",
            "ingest",
        ],
        description="KOS 知识摄取入口",
    ),
    BosService(
        uri="bos://memory/kos/schema",
        domain="memory",
        package="kos",
        action="schema",
        transport="stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/knowledge/kairon",
            "python",
            "-m",
            "kos.cli",
            "schema",
        ],
        description="KOS Schema 查询",
    ),
    BosService(
        uri="bos://memory/kronos/ingest",
        domain="memory",
        package="kronos",
        action="ingest",
        transport="stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/knowledge/kairon",
            "python",
            "-m",
            "kronos.cli",
            "ingest",
        ],
        description="Kronos 知识摄取管线入口",
    ),
    BosService(
        uri="bos://memory/kronos/scan",
        domain="memory",
        package="kronos",
        action="scan",
        transport="stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/knowledge/kairon",
            "python",
            "-m",
            "kronos.cli",
            "scan",
        ],
        description="Kronos 扫描入口",
    ),
    # ════════════════════════════════════════════════════════════════
    # Domain: governance (8)
    # ════════════════════════════════════════════════════════════════
    BosService(
        uri="bos://governance/metaos/decide",
        domain="governance",
        package="metaos",
        action="decide",
        transport="stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/metaos",
            "python",
            "-m",
            "metaos.cli",
            "decide",
        ],
        description="MetaOS 决策门控",
    ),
    BosService(
        uri="bos://governance/metaos/immune",
        domain="governance",
        package="metaos",
        action="immune",
        transport="stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/metaos",
            "python",
            "-m",
            "metaos.cli",
            "immune",
        ],
        description="MetaOS 免疫响应",
    ),
    BosService(
        uri="bos://governance/metaos/route",
        domain="governance",
        package="metaos",
        action="route",
        transport="stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/metaos",
            "python",
            "-m",
            "metaos.cli",
            "route",
        ],
        description="MetaOS 路由决策",
    ),
    BosService(
        uri="bos://governance/omo/state",
        domain="governance",
        package="omo",
        action="state",
        transport="stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/omo",
            "python",
            "-m",
            "omo.cli",
            "state",
        ],
        description="OMO 状态查询",
    ),
    BosService(
        uri="bos://governance/omo/debt",
        domain="governance",
        package="omo",
        action="debt",
        transport="stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/omo",
            "python",
            "-m",
            "omo.cli",
            "debt",
        ],
        description="OMO 债务查询",
    ),
    BosService(
        uri="bos://governance/eidos/validate",
        domain="governance",
        package="eidos",
        action="validate",
        transport="stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/knowledge/kairon",
            "python",
            "-m",
            "eidos.cli",
            "validate",
        ],
        description="Eidos Schema 约束校验",
    ),
    BosService(
        uri="bos://governance/protocols-layer/trigger",
        domain="governance",
        package="protocols-layer",
        action="trigger",
        transport="stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/knowledge/kairon",
            "python",
            "-m",
            "protocols_layer.cli",
            "trigger",
        ],
        description="[UNIMPLEMENTED] Protocols Layer 触发器 — kairon 无 protocols_layer 包, 声明悬空 (A2/2026-07-13 deprecate); 能力实现另立项",
    ),
    # ════════════════════════════════════════════════════════════════
    # Domain: analysis (12)
    # ════════════════════════════════════════════════════════════════
    BosService(
        uri="bos://analysis/minerva/research",
        domain="analysis",
        package="minerva",
        action="research",
        transport="stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/knowledge/kairon",
            "python",
            "-m",
            "minerva.cli",
            "research",
        ],
        description="Minerva 深度研究入口",
    ),
    BosService(
        uri="bos://analysis/minerva/ask",
        domain="analysis",
        package="minerva",
        action="ask",
        transport="stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/knowledge/kairon",
            "python",
            "-m",
            "minerva.cli",
            "ask",
        ],
        description="Minerva 追问入口",
    ),
    BosService(
        uri="bos://analysis/minerva/summarize",
        domain="analysis",
        package="minerva",
        action="summarize",
        transport="stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/knowledge/kairon",
            "python",
            "-m",
            "minerva.cli",
            "summarize",
        ],
        description="Minerva 摘要入口",
    ),
    BosService(
        uri="bos://analysis/ontoderive/derive",
        domain="analysis",
        package="ontoderive",
        action="derive",
        transport="stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/knowledge/kairon",
            "python",
            "-m",
            "ontoderive.cli",
            "derive",
        ],
        description="OntoDerive 本体推导入口",
    ),
    BosService(
        uri="bos://analysis/ontoderive/validate",
        domain="analysis",
        package="ontoderive",
        action="validate",
        transport="stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/knowledge/kairon",
            "python",
            "-m",
            "ontoderive.cli",
            "validate",
        ],
        description="OntoDerive 推导验证",
    ),
    BosService(
        uri="bos://analysis/ontoderive/explain",
        domain="analysis",
        package="ontoderive",
        action="explain",
        transport="stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/knowledge/kairon",
            "python",
            "-m",
            "ontoderive.cli",
            "explain",
        ],
        description="OntoDerive 推导解释",
    ),
    BosService(
        uri="bos://analysis/codeanalyze/scan",
        domain="analysis",
        package="codeanalyze",
        action="scan",
        transport="stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/knowledge/kairon",
            "python",
            "-m",
            "codeanalyze.cli",
            "scan",
        ],
        description="CodeAnalyze AST 扫描入口",
    ),
    BosService(
        uri="bos://analysis/codeanalyze/analyze",
        domain="analysis",
        package="codeanalyze",
        action="analyze",
        transport="stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/knowledge/kairon",
            "python",
            "-m",
            "codeanalyze.cli",
            "analyze",
        ],
        description="CodeAnalyze 深度分析",
    ),
    BosService(
        uri="bos://analysis/codeanalyze/metrics",
        domain="analysis",
        package="codeanalyze",
        action="metrics",
        transport="stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/knowledge/kairon",
            "python",
            "-m",
            "codeanalyze.cli",
            "metrics",
        ],
        description="CodeAnalyze 代码度量",
    ),
    BosService(
        uri="bos://analysis/iris/discover",
        domain="analysis",
        package="iris",
        action="discover",
        transport="stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/knowledge/kairon",
            "python",
            "-m",
            "iris.cli",
            "discover",
        ],
        description="Iris 发现入口",
    ),
    BosService(
        uri="bos://analysis/iris/scan",
        domain="analysis",
        package="iris",
        action="scan",
        transport="stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/knowledge/kairon",
            "python",
            "-m",
            "iris.cli",
            "scan",
        ],
        description="Iris 扫描入口",
    ),
    BosService(
        uri="bos://analysis/iris/recall",
        domain="analysis",
        package="iris",
        action="recall",
        transport="stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/knowledge/kairon",
            "python",
            "-m",
            "iris.cli",
            "recall",
        ],
        description="Iris 召回入口",
    ),
    # ════════════════════════════════════════════════════════════════
    # Domain: persona (8)
    # ════════════════════════════════════════════════════════════════
    BosService(
        uri="bos://persona/bdsk/evaluate",
        domain="persona",
        package="agora",
        action="persona-evaluate",
        transport="internal",
        module_path="agora.server.tools_bos",
        func_name="persona_bdsk_evaluate",
        description=(
            "B.D.S.K. 虚拟董事会评审网关；唯一推理链为 "
            "bos://compute/aetherforge/infer，失败返回 not_proven，禁止自动 ADR"
        ),
    ),
    BosService(
        uri="bos://persona/core-models/schema",
        domain="persona",
        package="core-models",
        action="schema",
        transport="stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/knowledge/kairon",
            "python",
            "-m",
            "core_models.cli",
            "schema",
        ],
        description="Core Models Schema 查询",
    ),
    BosService(
        uri="bos://persona/core-models/validate",
        domain="persona",
        package="core-models",
        action="validate",
        transport="stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/knowledge/kairon",
            "python",
            "-m",
            "core_models.cli",
            "validate",
        ],
        description="Core Models 校验",
    ),
    BosService(
        uri="bos://persona/health-profile/query",
        domain="persona",
        package="health-profile",
        action="query",
        transport="stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/knowledge/kairon",
            "python",
            "-m",
            "health_profile.cli",
            "query",
        ],
        description="Health Profile 查询",
    ),
    BosService(
        uri="bos://persona/health-profile/update",
        domain="persona",
        package="health-profile",
        action="update",
        transport="stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/knowledge/kairon",
            "python",
            "-m",
            "health_profile.cli",
            "update",
        ],
        description="Health Profile 更新",
    ),
    BosService(
        uri="bos://persona/sot-bridge-persona/recall-entity",
        domain="persona",
        package="sot-bridge-persona",
        action="recall-entity",
        transport="internal",
        module_path="agora.mcp.bos_resolver",
        func_name="_sharedbrain_bridge_recall_entity",
        description="SharedBrain Bridge 实体召回 (P36-W1 GAP 补全, canonical URI)",
    ),
    # ════════════════════════════════════════════════════════════════
    # Domain: capability (8)
    # ════════════════════════════════════════════════════════════════
    BosService(
        uri="bos://capability/agent-runtime/execute",
        domain="capability",
        package="agent-runtime",
        action="execute",
        transport="mcp_stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/runtime",
            "python",
            "-m",
            "runtime.mcp_server",
        ],
        description="Agent Runtime 执行入口",
    ),
    BosService(
        uri="bos://capability/agent-runtime/list-tools",
        domain="capability",
        package="agent-runtime",
        action="list-tools",
        transport="mcp_stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/runtime",
            "python",
            "-m",
            "runtime.mcp_server",
        ],
        description="Agent Runtime 工具列表",
    ),
    BosService(
        uri="bos://capability/agent-runtime/status",
        domain="capability",
        package="agent-runtime",
        action="status",
        transport="mcp_stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/runtime",
            "python",
            "-m",
            "runtime.mcp_server",
        ],
        description="Agent Runtime 状态",
    ),
    BosService(
        uri="bos://capability/swarm/run",
        domain="capability",
        package="swarm",
        action="run",
        transport="stdio",
        command=[
            "uv",
            "run",
            "--package",
            "aetherforge",
            "python",
            "-m",
            "aetherforge.cli",
            "swarm",
            "run",
        ],
        description="AetherForge Swarm 执行入口",
    ),
    BosService(
        uri="bos://capability/forge/agent-list",
        domain="capability",
        package="forge",
        action="agent-list",
        transport="stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/knowledge/kairon",
            "python",
            "-m",
            "forge.cli",
            "agent-list",
        ],
        description="Forge 集市 Agent 列表",
    ),
    BosService(
        uri="bos://capability/forge/agent-install",
        domain="capability",
        package="forge",
        action="agent-install",
        transport="stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/knowledge/kairon",
            "python",
            "-m",
            "forge.cli",
            "agent-install",
        ],
        description="Forge 集市 Agent 安装",
    ),
    BosService(
        uri="bos://capability/forge/registry",
        domain="capability",
        package="forge",
        action="registry",
        transport="stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/knowledge/kairon",
            "python",
            "-m",
            "forge.cli",
            "registry",
        ],
        description="Forge 注册表查询",
    ),
    BosService(
        uri="bos://capability/forge/publish",
        domain="capability",
        package="forge",
        action="publish",
        transport="stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/knowledge/kairon",
            "python",
            "-m",
            "forge.cli",
            "publish",
        ],
        description="Forge 发布入口",
    ),
    BosService(
        uri="bos://capability/forge/lint",
        domain="capability",
        package="forge",
        action="lint",
        transport="stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/knowledge/kairon",
            "python",
            "-m",
            "forge.cli",
            "lint",
        ],
        description="Forge Lint 检查",
    ),
    # ════════════════════════════════════════════════════════════════
    # MCP-stdio services (from legacy POC_SERVICES dict)
    # ════════════════════════════════════════════════════════════════
    BosService(
        uri="bos://persona/family-hub/health",
        domain="persona",
        package="family-hub",
        action="health",
        transport="mcp_stdio",
        command=["uv", "run", "python", "projects/family-hub/mcp_server.py"],
        description="Family Hub local MCP Server",
    ),
    BosService(
        uri="bos://governance/omo/sync",
        domain="governance",
        package="omo",
        action="sync",
        transport="mcp_stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/omo",
            "python",
            "-m",
            "omo",
            "serve",
        ],
        description="OMO 状态同步 (mcp_stdio transport 跨进程)",
    ),
    BosService(
        uri="bos://governance/l4-kernel/domains",
        domain="governance",
        package="l4-kernel",
        action="mcp",
        transport="mcp_stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/l4-kernel",
            "python",
            "-m",
            "l4_kernel.mcp_server",
        ],
        description="L4 Domain Kernel MCP — 24域管理",
    ),
    BosService(
        uri="bos://l4-kernel/domains",
        domain="governance",
        package="l4-kernel",
        action="mcp",
        transport="mcp_stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/l4-kernel",
            "python",
            "-m",
            "l4_kernel.mcp_server",
        ],
        description="L4 Kernel MCP (短路径别名)",
    ),
    BosService(
        uri="bos://capability/runtime/health",
        domain="capability",
        package="runtime",
        action="mcp",
        transport="mcp_stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/runtime",
            "python",
            "-m",
            "runtime.mcp_server",
        ],
        description="Runtime MCP — 服务注册表/健康/协议/KEI",
    ),
    BosService(
        uri="bos://runtime/health",
        domain="capability",
        package="runtime",
        action="mcp",
        transport="mcp_stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/runtime",
            "python",
            "-m",
            "runtime.mcp_server",
        ],
        description="Runtime MCP (短路径别名)",
    ),
    # [UNIMPLEMENTED] POC stdio URIs — 标记为 mcp_stdio 但无 serve CLI
    BosService(
        uri="bos://analysis/minerva/draft",
        domain="analysis",
        package="minerva",
        action="draft",
        transport="mcp_stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/knowledge/kairon",
            "python",
            "-m",
            "minerva",
            "serve",
            "--action",
            "draft",
        ],
        description="[UNIMPLEMENTED] Minerva 草稿生成 (POC stdio)",
    ),
    BosService(
        uri="bos://analysis/minerva/audit",
        domain="analysis",
        package="minerva",
        action="audit",
        transport="mcp_stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/knowledge/kairon",
            "python",
            "-m",
            "minerva",
            "serve",
            "--action",
            "audit",
        ],
        description="[UNIMPLEMENTED] Minerva 审计 (POC stdio)",
    ),
    BosService(
        uri="bos://analysis/ontoderive/audit",
        domain="analysis",
        package="ontoderive",
        action="audit",
        transport="mcp_stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/knowledge/kairon",
            "python",
            "-m",
            "ontoderive",
            "serve",
            "--action",
            "audit",
        ],
        description="[UNIMPLEMENTED] Ontoderive 审计 (POC stdio)",
    ),
    BosService(
        uri="bos://analysis/ontoderive/fact-check",
        domain="analysis",
        package="ontoderive",
        action="fact-check",
        transport="mcp_stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/knowledge/kairon",
            "python",
            "-m",
            "ontoderive",
            "serve",
            "--action",
            "fact-check",
        ],
        description="[UNIMPLEMENTED] Ontoderive 事实校验 (POC stdio)",
    ),
    BosService(
        uri="bos://analysis/codeanalyze/report",
        domain="analysis",
        package="codeanalyze",
        action="report",
        transport="mcp_stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/knowledge/kairon",
            "python",
            "-m",
            "codeanalyze",
            "serve",
            "--action",
            "report",
        ],
        description="[UNIMPLEMENTED] CodeAnalyze 分析报告 (POC stdio)",
    ),
    BosService(
        uri="bos://analysis/codeanalyze/lint",
        domain="analysis",
        package="codeanalyze",
        action="lint",
        transport="mcp_stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/knowledge/kairon",
            "python",
            "-m",
            "codeanalyze",
            "serve",
            "--action",
            "lint",
        ],
        description="[UNIMPLEMENTED] CodeAnalyze Lint (POC stdio)",
    ),
    BosService(
        uri="bos://analysis/iris/connect",
        domain="analysis",
        package="iris",
        action="connect",
        transport="mcp_stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/knowledge/kairon",
            "python",
            "-m",
            "iris",
            "serve",
            "--action",
            "connect",
        ],
        description="[UNIMPLEMENTED] Iris 连接 (POC stdio)",
    ),
    BosService(
        uri="bos://analysis/iris/transform",
        domain="analysis",
        package="iris",
        action="transform",
        transport="mcp_stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/knowledge/kairon",
            "python",
            "-m",
            "iris",
            "serve",
            "--action",
            "transform",
        ],
        description="[UNIMPLEMENTED] Iris 数据转换 (POC stdio)",
    ),
    BosService(
        uri="bos://analysis/iris/validate",
        domain="analysis",
        package="iris",
        action="validate",
        transport="mcp_stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/knowledge/kairon",
            "python",
            "-m",
            "iris",
            "serve",
            "--action",
            "validate",
        ],
        description="[UNIMPLEMENTED] Iris 数据校验 (POC stdio)",
    ),
    BosService(
        uri="bos://persona/health-profile/summary",
        domain="persona",
        package="health-profile",
        action="summary",
        transport="mcp_stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/knowledge/kairon",
            "python",
            "-m",
            "health_profile",
            "serve",
            "--action",
            "summary",
        ],
        description="[UNIMPLEMENTED] Health-Profile 健康摘要 (POC stdio)",
    ),
    BosService(
        uri="bos://persona/health-profile/alert",
        domain="persona",
        package="health-profile",
        action="alert",
        transport="mcp_stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/knowledge/kairon",
            "python",
            "-m",
            "health_profile",
            "serve",
            "--action",
            "alert",
        ],
        description="[UNIMPLEMENTED] Health-Profile 健康告警 (POC stdio)",
    ),
    BosService(
        uri="bos://capability/forge/discover",
        domain="capability",
        package="forge",
        action="discover",
        transport="mcp_stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/knowledge/kairon",
            "python",
            "-m",
            "forge",
            "serve",
            "--action",
            "discover",
        ],
        description="[UNIMPLEMENTED] Forge 工具发现 (POC stdio)",
    ),
    BosService(
        uri="bos://capability/forge/exec-tool",
        domain="capability",
        package="forge",
        action="exec-tool",
        transport="mcp_stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/knowledge/kairon",
            "python",
            "-m",
            "forge",
            "serve",
            "--action",
            "exec-tool",
        ],
        description="[UNIMPLEMENTED] Forge 工具执行 (POC stdio)",
    ),
    BosService(
        uri="bos://capability/forge/list-tools",
        domain="capability",
        package="forge",
        action="list-tools",
        transport="mcp_stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/knowledge/kairon",
            "python",
            "-m",
            "forge",
            "serve",
            "--action",
            "list-tools",
        ],
        description="[UNIMPLEMENTED] Forge 工具列表 (POC stdio)",
    ),
    BosService(
        uri="bos://capability/forge/register-tool",
        domain="capability",
        package="forge",
        action="register-tool",
        transport="mcp_stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/knowledge/kairon",
            "python",
            "-m",
            "forge",
            "serve",
            "--action",
            "register-tool",
        ],
        description="[UNIMPLEMENTED] Forge 工具注册 (POC stdio)",
    ),
    BosService(
        uri="bos://memory/kronos/query",
        domain="memory",
        package="kronos",
        action="query",
        transport="mcp_stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/knowledge/kairon",
            "python",
            "-m",
            "kronos",
            "serve",
            "--action",
            "query",
        ],
        description="[UNIMPLEMENTED] KRONOS 时间序列查询 (POC stdio)",
    ),
    BosService(
        uri="bos://memory/kronos/schedule",
        domain="memory",
        package="kronos",
        action="schedule",
        transport="mcp_stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/knowledge/kairon",
            "python",
            "-m",
            "kronos",
            "serve",
            "--action",
            "schedule",
        ],
        description="[UNIMPLEMENTED] KRONOS 调度任务 (POC stdio)",
    ),
    BosService(
        uri="bos://governance/metaos/gate",
        domain="governance",
        package="metaos",
        action="gate",
        transport="mcp_stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/metaos",
            "python",
            "-m",
            "metaos",
            "serve",
            "--action",
            "gate",
        ],
        description="MetaOS 门控检查 (POC stdio)",
    ),
    BosService(
        uri="bos://governance/metaos/register",
        domain="governance",
        package="metaos",
        action="register",
        transport="mcp_stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/metaos",
            "python",
            "-m",
            "metaos",
            "serve",
            "--action",
            "register",
        ],
        description="MetaOS 包注册 (POC stdio)",
    ),
    BosService(
        uri="bos://compute/aetherforge/infer",
        domain="compute",
        package="aetherforge",
        action="infer",
        transport="stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/aetherforge",
            "python",
            "-m",
            "aetherforge.cli",
            "infer",
        ],
        description="AetherForge 算力网关与 omlxc (Apple MLX/Local LLM) 本地量化模型通用推理调度端点",
    ),
    BosService(
        uri="bos://compute/aetherforge/mesh",
        domain="compute",
        package="aetherforge",
        action="mesh",
        transport="stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/aetherforge",
            "python",
            "-m",
            "aetherforge.cli",
            "mesh",
        ],
        description="AetherForge 边缘多节点网格状态与拓扑健康度查询端点 (oMLXC Compute Mesh)",
    ),
    BosService(
        uri="bos://compute/aetherforge/profile",
        domain="compute",
        package="aetherforge",
        action="profile",
        transport="stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/aetherforge",
            "python",
            "-m",
            "aetherforge.cli",
            "profile",
        ],
        description="AetherForge 硬件性能特征剖析与模型量化适配检查端点 (Hardware Profile)",
    ),
    BosService(
        uri="bos://compute/aetherforge/fabric",
        domain="compute",
        package="aetherforge",
        action="fabric",
        transport="stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/omlxc",
            "omlxc",
            "fabric",
            "inspect",
            "--json",
        ],
        description="omlxc Compute Fabric 异构算力拓扑、硬件温控、显存预算与分诊状态诊断端点",
    ),
    BosService(
        uri="bos://compute/aetherforge/triage",
        domain="compute",
        package="aetherforge",
        action="triage",
        transport="stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/omlxc",
            "omlxc",
            "fabric",
            "triage",
        ],
        description="omlxc Intent Triage 意图复杂度轻量初筛与模型等级决策端点",
    ),
    BosService(
        uri="bos://compute/aetherforge/vram",
        domain="compute",
        package="aetherforge",
        action="vram",
        transport="stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/omlxc",
            "omlxc",
            "fabric",
            "vram",
        ],
        description="omlxc VRAM Budget 动态 KV Cache 显存预算与准入判定端点",
    ),
    BosService(
        uri="bos://compute/aetherforge/warm",
        domain="compute",
        package="aetherforge",
        action="warm",
        transport="stdio",
        command=[
            "uv",
            "run",
            "--directory",
            "projects/omlxc",
            "omlxc",
            "fabric",
            "warm",
            "--json",
        ],
        description="omlxc System Prefix Warmer 系统前缀缓存预热端点",
    ),
]

# ── POC_SERVICES: YAML 驱动加载器 ──────────────────────────
# 向后兼容：所有 from .services import POC_SERVICES 继续工作


def _fallback_services() -> list[BosService]:
    """硬编码 fallback + internal transport 单源 (services_internal)."""
    from .services_internal import _INTERNAL_SERVICES

    return list(_FALLBACK_SERVICES) + list(_INTERNAL_SERVICES)


def _load_services() -> list[BosService]:
    """加载 BOS 服务注册表，优先 YAML 声明式，fallback 到硬编码。

    加载顺序:
    1. AGORA_BOS_REGISTRY 环境变量指定的 YAML 路径
    2. etc/bos-services.yaml (项目默认)
    3. _FALLBACK_SERVICES + _INTERNAL_SERVICES (硬编码，零依赖)
    """
    # env=none → 强制 fallback
    if os.environ.get("AGORA_BOS_REGISTRY", "").lower() == "none":
        return _fallback_services()

    candidates = []
    env_path = os.environ.get("AGORA_BOS_REGISTRY", "")
    if env_path:
        candidates.append(env_path)

    # 项目默认路径
    here = os.path.dirname(os.path.abspath(__file__))
    # resolver/ → mcp/ → resolver/ → agora/ → src/ → agora/ → projects/ → workspace/
    # 更健壮的方式：通过 _resolve_agora_root 找到项目根
    try:
        from agora.mcp.resolver.bos_registry import DEFAULT_REGISTRY_PATH

        default_yaml = str(DEFAULT_REGISTRY_PATH)
    except Exception:  # defensive fallback
        default_yaml = os.path.join(
            here, "..", "..", "..", "..", "etc", "bos-services.yaml"
        )
    candidates.append(os.path.normpath(default_yaml))

    for path in candidates:
        if os.path.exists(path):
            try:
                from agora.mcp.resolver.bos_registry import load_from_yaml

                return load_from_yaml(path)
            except Exception as exc:  # defensive fallback
                import logging

                logging.getLogger(__name__).warning(
                    "BOS YAML 加载失败 (%s), 使用 fallback: %s", path, exc
                )
                break

    return _fallback_services()


POC_SERVICES: list[BosService] = _load_services()
